"""Neat-liquid systems: NPT MD, density evaluation, and density derivatives.

Each liquid runs one independent NPT trajectory per temperature. All
temperatures share a single key file whose PARAMETERS line is rewritten once
per optimizer step, so a step never has to touch more than one key.

The density derivative with respect to a parameter comes from the fluctuation
formula rather than from rerunning MD::

    d<rho>/dl = -beta ( <rho dE/dl> - <rho><dE/dl> )

which is Eq. 4 of Wang et al. (2013). ``dE/dl`` is a per-frame central
difference obtained by re-analyzing the *existing* production trajectory under
perturbed parameters, so a Jacobian costs single-point energies instead of
fresh dynamics.
"""

import logging
import os
from pathlib import Path

import numpy as np

from . import tinkerio
from .dispatch import Job

log = logging.getLogger(__name__)


class NeatLiquidSystem:
    """One neat liquid simulated across one or more temperatures."""

    def __init__(self, cfg, workdir, tinker_env, param_file, stall_timeout=0.0):
        self.cfg = cfg
        self.name = cfg.name
        self.dir = os.path.join(workdir, cfg.name)
        self.tinker_env = tinker_env
        self.param_file = param_file
        self.stall_timeout = stall_timeout
        self.total_mass = None
        self.key_file = os.path.join(self.dir, f"{self.name}.key")
        self._rho_frames = None

    # -- naming -----------------------------------------------------------

    def _tag(self, T):
        return f"_{T:.0f}K"

    def _base(self, T):
        return f"{self.name}{self._tag(T)}"

    def arc_path(self, T):
        return os.path.join(self.dir, f"{self._base(T)}.arc")

    def prod_arc(self, T):
        return os.path.join(self.dir, f"{self._base(T)}-prod.arc")

    def log_path(self, T):
        return os.path.join(self.dir, f"{self._base(T)}.log")

    def err_path(self, T):
        """Where Tinker dumps coordinates when dynamics blow up."""
        return os.path.join(self.dir, f"{self._base(T)}.err")

    # -- setup ------------------------------------------------------------

    def setup(self, dry_run=False):
        """Create the working directory, key, coordinate links and MD scripts."""
        os.makedirs(self.dir, exist_ok=True)

        xyz_local = os.path.join(self.dir, f"{self.name}.xyz")
        tinkerio.force_symlink(self.cfg.box_xyz, xyz_local)

        # The neat liquid needs a plain NPT key: an HFE key carries lambda and
        # ligand keywords that would alchemically decouple part of the box.
        if not os.path.isfile(self.key_file):
            src = self.cfg.key or tinkerio.package_data('liquid.key')
            tinkerio.derive_liquid_key(src, self.key_file)
            log.info("[%s] generated neat-liquid key %s from %s",
                     self.name, os.path.basename(self.key_file), src)
        self.update_key(self.param_file.working)

        self.total_mass = tinkerio.parse_system_mass(xyz_local, self.param_file.snapshot)
        log.info("[%s] total system mass %.4f g/mol", self.name, self.total_mass)

        for T in self.cfg.temperatures:
            self._write_md_script(T)
        return self

    def update_key(self, prm_path):
        """Point the shared key's PARAMETERS line at *prm_path*."""
        with open(self.key_file) as f:
            contents = f.read()
        with open(self.key_file, 'w') as f:
            f.write(tinkerio.rewrite_parameters_line(contents, prm_path))

    def _write_md_script(self, T, remaining_steps=None, append_log=False, suffix=''):
        c = self.cfg
        base = self._base(T)
        xyz_name, key_name = f"{base}.xyz", f"{base}.key"
        log_name = f"{base}.log"
        sh_name = f"{base}{suffix}.sh"

        # Per-temperature name-alikes so Tinker writes one arc per temperature,
        # while the key symlink keeps them all on the shared key file.
        xyz_path = os.path.join(self.dir, xyz_name)
        key_path = os.path.join(self.dir, key_name)
        if not os.path.islink(xyz_path) and not os.path.isfile(xyz_path):
            os.symlink(f"{self.name}.xyz", xyz_path)
        if not os.path.islink(key_path):
            tinkerio.force_symlink(f"{self.name}.key", key_path)

        steps = c.total_steps if remaining_steps is None else remaining_steps
        redirect = '>>' if append_log else '>'
        lines = [
            "#!/bin/bash",
            f"source {self.tinker_env}",
            f"# Neat-liquid NPT MD for '{self.name}' at {T} K — generated by autoff",
            f"# timestep {c.time_step} fs | output {c.write_freq} ps "
            f"({c.steps_per_frame} steps/frame) | pressure {c.pressure} atm",
            f"# equilibration {c.n_equil} frames | production {c.n_production} frames",
            "",
            f"$DYNAMIC9 {xyz_name} -k {key_name} {steps} {c.time_step} "
            f"{c.write_freq} 4 {T} {c.pressure} {redirect} {log_name}",
            "",
        ]
        sh_path = os.path.join(self.dir, sh_name)
        with open(sh_path, 'w') as f:
            f.write("\n".join(lines))
        return sh_name

    # -- MD ---------------------------------------------------------------

    def md_jobs(self, fresh=False):
        """Return the MD jobs still needed.

        With *fresh* set (an optimizer trial point) the old trajectory is
        deleted first, because it was generated under different parameters.
        Otherwise a complete trajectory is reused and a partial one is resumed
        from its .dyn checkpoint.
        """
        c = self.cfg
        n_total = c.n_equil + c.n_production
        jobs = []

        for T in self.cfg.temperatures:
            arc, dyn = self.arc_path(T), os.path.join(self.dir, f"{self._base(T)}.dyn")
            sh_name = f"{self._base(T)}.sh"

            if fresh:
                Path(arc).unlink(missing_ok=True)
                Path(dyn).unlink(missing_ok=True)
                Path(self.log_path(T)).unlink(missing_ok=True)
                self._clear_crash(T)
                self._write_md_script(T)
                jobs.append(self._job(sh_name, T))
                continue

            n_done = tinkerio.count_arc_frames(arc)
            if n_done >= n_total:
                log.info("[%s] T=%.1fK: trajectory already complete (%d/%d frames)",
                         self.name, T, n_done, n_total)
                continue
            if n_done > 0 and os.path.isfile(dyn):
                remaining = (n_total - n_done) * c.steps_per_frame
                log.info("[%s] T=%.1fK: resuming, %d/%d frames done, %d steps left",
                         self.name, T, n_done, n_total, remaining)
                self._clear_crash(T)
                # Append to the log so densities from the earlier segment survive
                resume_sh = self._write_md_script(T, remaining_steps=remaining,
                                                  append_log=True, suffix='-resume')
                jobs.append(self._job(resume_sh, T))
            else:
                log.info("[%s] T=%.1fK: starting fresh MD", self.name, T)
                self._clear_crash(T)
                self._write_md_script(T)
                jobs.append(self._job(sh_name, T))
        return jobs

    def _clear_crash(self, T):
        """Drop the previous run's crash dump before launching a new one.

        Whether a .err file means anything depends on which run wrote it, so
        every submission starts from a clean slate: afterwards its presence
        can only describe the run that is current.
        """
        Path(self.err_path(T)).unlink(missing_ok=True)

    def _job(self, sh_name, T):
        return Job(script=sh_name, workdir=self.dir, queue='GPU', nproc=2,
                   label=f"{self.name}@{T:.0f}K md")

    def md_complete(self):
        """True once every temperature has a full-length trajectory.

        Raises RuntimeError if a trajectory stopped short because its dynamics
        died. Nothing in this pipeline resubmits, so a crashed run left to the
        frame count alone reads as "still going" forever; the caller polls a
        counter that will never move again and the whole fit hangs in silence.

        Two ways a run ends early, and both have to be caught here. A blow-up
        announces itself in the log or a .err dump. A silent death -- an
        eviction, an OOM kill, a node that went away -- announces nothing at
        all, and is recognised only by output that has stopped arriving.
        """
        n_total = self.cfg.n_equil + self.cfg.n_production
        pending, crashed = [], []
        for T in self.cfg.temperatures:
            n_done = tinkerio.count_arc_frames(self.arc_path(T))
            if n_done >= n_total:
                continue
            reason = tinkerio.md_crash_reason(self.log_path(T), self.err_path(T))
            if not reason:
                reason = tinkerio.stall_reason(
                    self.stall_timeout, self.arc_path(T), self.log_path(T))
            if reason:
                crashed.append(f"T={T:.0f}K ({n_done}/{n_total} frames): {reason}")
            else:
                pending.append(f"T={T:.0f}K ({n_done}/{n_total})")

        if crashed:
            raise RuntimeError(
                f"[{self.name}] MD died at {len(crashed)} temperature(s) and will "
                f"not finish on its own:\n  " + "\n  ".join(crashed) +
                f"\nInspect the logs in {self.dir}. A polarization or integration "
                f"failure usually means the current parameters are unphysical; "
                f"output that simply stopped usually means the job was lost with "
                f"its node, and rerunning that temperature's .sh resumes it."
            )
        if pending:
            log.info("[%s] waiting on MD: %s", self.name, ", ".join(pending))
            return False
        return True

    # -- properties -------------------------------------------------------

    def densities(self):
        """Return mean density per temperature, caching the per-frame values.

        Densities come from the box line of each .arc frame. The trajectory is
        the record of what was simulated, and it is also what the reweighted
        energies behind the density derivative are computed over, so taking
        both series from one file keeps them frame-for-frame aligned. The MD
        log is flushed separately and can end at a different length.
        """
        means, frames = [], []
        for T in self.cfg.temperatures:
            rho, n_parsed = tinkerio.parse_arc_densities(
                self.arc_path(T), self.total_mass,
                self.cfg.n_equil, self.cfg.n_production)
            if len(rho) == 0:
                raise RuntimeError(
                    f"[{self.name}] T={T:.0f}K: no production frames after dropping "
                    f"{self.cfg.n_equil} equilibration frames (parsed {n_parsed} total). "
                    f"Check {self.arc_path(T)}."
                )
            if len(rho) != self.cfg.n_production:
                log.warning(
                    "[%s] T=%.0fK: expected %d production frames, found %d; "
                    "using what is available", self.name, T, self.cfg.n_production, len(rho))
            frames.append(rho)
            means.append(float(rho.mean()))
        self._rho_frames = frames
        return means

    @property
    def rho_frames(self):
        return self._rho_frames

    # -- Jacobian ---------------------------------------------------------

    def analyze_jobs(self, sidecar_indices):
        """Trim trajectories to production and write one analyze job per (sidecar, T).

        Returns (jobs, log_map) where log_map keys are (sidecar_index, temp_index).
        """
        for T in self.cfg.temperatures:
            full, prod = self.arc_path(T), self.prod_arc(T)
            n_total = tinkerio.count_arc_frames(full)
            start = tinkerio.production_start(
                n_total, self.cfg.n_equil, self.cfg.n_production)
            log.info("[%s] trimming production arc for T=%.0fK "
                     "(frames %d-%d of %d)",
                     self.name, T, start + 1, n_total, n_total)
            tinkerio.trim_arc_to_production(
                full, prod, self.cfg.n_equil, self.cfg.n_production)
            # The full arc is large and already summarized by prod; keeping it
            # would double the footprint of every optimizer step.
            Path(full).unlink(missing_ok=True)

        jobs, log_map = [], {}
        for idx in sidecar_indices:
            prm = self.param_file.sidecar(idx)
            for ti, T in enumerate(self.cfg.temperatures):
                if (idx, ti) in log_map:
                    continue
                sh_name, log_path = self._write_analyze_script(prm, idx, T)
                log_map[(idx, ti)] = log_path
                jobs.append(Job(script=sh_name, workdir=self.dir, queue='GPU', nproc=2,
                                label=f"{self.name}@{T:.0f}K analyze prm{idx:02d}"))
        self._analyze_logs = log_map
        return jobs, log_map

    def _write_analyze_script(self, prm_path, idx, T):
        label = f"{self._base(T)}-prm{idx:02d}"
        key_name, sh_name, log_name = f"{label}.key", f"{label}-analyze.sh", f"{label}-analyze.log"

        with open(self.key_file) as f:
            contents = f.read()
        with open(os.path.join(self.dir, key_name), 'w') as f:
            f.write(tinkerio.rewrite_parameters_line(contents, prm_path))

        # A leftover log from the previous step would read as already complete
        Path(os.path.join(self.dir, log_name)).unlink(missing_ok=True)

        lines = [
            "#!/bin/bash",
            f"source {self.tinker_env}",
            f"$ANALYZE9 {os.path.basename(self.prod_arc(T))} -k {key_name} E > {log_name}",
            "",
        ]
        with open(os.path.join(self.dir, sh_name), 'w') as f:
            f.write("\n".join(lines))
        return sh_name, os.path.join(self.dir, log_name)

    def analyze_complete(self, log_map):
        """True once every analyze log holds a full set of frame energies."""
        n_expected = self.cfg.n_production
        pending = []
        for (idx, ti), path in log_map.items():
            count = tinkerio.count_analyze_energies(path)
            if count < n_expected:
                pending.append(f"{os.path.basename(path)} ({count}/{n_expected})")
        if pending:
            log.info("[%s] waiting on %d analyze job(s): %s", self.name, len(pending),
                     ", ".join(pending[:4]) + (" ..." if len(pending) > 4 else ""))
            return False
        return True

    def jacobian_columns(self, log_map, perturb_map, diff_step):
        """Return the density Jacobian rows for this liquid.

        Result shape is (n_temperatures, n_free_params); row order matches
        ``cfg.temperatures``.
        """
        n_params = len(perturb_map)
        J = np.zeros((len(self.cfg.temperatures), n_params))
        energies = {key: tinkerio.parse_analyze_energies(path)
                    for key, path in log_map.items()}

        for ti, beta in enumerate(self.cfg.betas):
            rho = self._rho_frames[ti]
            for j in range(n_params):
                plus_idx, minus_idx = perturb_map[j]
                E_plus = energies[(plus_idx, ti)]
                E_minus = energies[(minus_idx, ti)]
                n = min(len(rho), len(E_plus), len(E_minus))
                J[ti, j] = _density_derivative(
                    rho[:n], E_plus[:n], E_minus[:n], beta, diff_step)
        return J


def _density_derivative(rho_frames, E_plus, E_minus, beta, diff_step):
    """d<rho>/dl via the fluctuation formula (Wang et al. 2013, Eq. 4)."""
    dEdl = (E_plus - E_minus) / (2.0 * diff_step)
    return -beta * float((rho_frames * dEdl).mean() - rho_frames.mean() * dEdl.mean())
